services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  app:
    image: guokuojlu/gnomon-app-flow:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
