name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:latest})

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: guokuojlu
        password: ${{ secrets.DOCKER_HUB_PWD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: guokuojlu/gnomon-app-flow:${RELEASE_VERSION}